# Generated by Django 4.1.3 on 2022-11-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_api_token', models.CharField(max_length=100)),
                ('start_of_time_frame', models.DateField()),
                ('end_of_time_frame', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='day_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
                ('type', models.CharField(max_length=5)),
                ('working_hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='public_holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='toggl_clients',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='toggl_workspaces',
            fields=[
                ('wid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vacation_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='toggl_projects',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing_app.toggl_clients')),
            ],
        ),
        migrations.AddField(
            model_name='toggl_clients',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing_app.toggl_workspaces'),
        ),
        migrations.CreateModel(
            name='time_entries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing_app.toggl_projects')),
            ],
        ),
    ]
